customhost = "database-1.cccqxqfsmyxw.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "tanchenxun-employee"
custombucket = "tanchenxun-employee"
customregion = "us-east-1"
